import mongoose from 'mongoose';

const emailLogSchema = new mongoose.Schema(
  {
    contact_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Contact',
      required: [true, 'contact_id is required'],
      index: true
    },
    direction: {
      type: String,
      enum: ['outbound', 'inbound'],
      required: [true, 'direction is required']
    },
    subject: {
      type: String,
      trim: true
    },
    body: {
      type: String
    },
    html_body: {
      type: String
    },
    llm_generated: {
      type: Boolean,
      default: false
    },
    // "draft_pending" = generated by LLM, awaiting human approval before send
    // "sent"          = successfully delivered via Gmail API
    // "failed"        = send attempt failed
    // "received"      = inbound reply logged from inbox poll
    log_status: {
      type: String,
      enum: ['draft_pending', 'sent', 'failed', 'received'],
      default: 'sent'
    },
    sent_at: {
      type: Date
    },
    opened_at: {
      type: Date
    },
    // Classification of inbound reply by LLM
    classification: {
      type: String,
      enum: [
        'interested',
        'not_interested',
        'auto_reply',
        'bounce',
        'out_of_office',
        'unclear',
        null
      ],
      default: null
    },
    // One-line reasoning from the classifier
    classification_reason: {
      type: String
    },
    raw_reply_text: {
      type: String
    },
    // Gmail API identifiers for thread-matching replies
    gmail_message_id: {
      type: String,
      sparse: true,
      index: true
    },
    gmail_thread_id: {
      type: String,
      sparse: true,
      index: true
    }
  },
  {
    timestamps: true
  }
);

// Index for rate-limiting queries (count sent in last N hours)
emailLogSchema.index({ direction: 1, sent_at: -1 });

// Index for fetching pending drafts quickly
emailLogSchema.index({ log_status: 1, createdAt: -1 });

const EmailLog = mongoose.model('EmailLog', emailLogSchema);

export default EmailLog;
